default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', 'localhost') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>

development:
  <<: *default
  database: rails_dev_development

test:
  <<: *default
  database: rails_dev_test

production:
  <<: *default
  database: rails_dev_production
  username: rails_dev
  password: <%= ENV['RAILS_DEV_DATABASE_PASSWORD'] %>
